---
# tasks file for ansible-rtorrent configure_systemd

- name: "create rtorrent systemd service"
  template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service
    owner: root
    group: root
    mode: 0755
  tags:
    - service

- name: "start rtorrent service"
  service:
    name: rtorrent
    state: started
    enabled: yes
  tags:
    - service
