---
# tasks file for ansible-rtorrent configure_upstart

- name: "create rtorrent upstart service"
  template:
    src: rtorrent.conf.j2
    dest: /etc/init/rtorrent.conf
    owner: root
    group: root
    mode: 0755
  notify: restart rtorrent
  tags:
    - service
