- name: install rtorrent
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - rtorrent
    - tmux

- name: create rtorrent group
  sudo: yes
  group:
    name: "{{ rtorrent_group }}"

- name: create rtorrent user
  sudo: yes
  user:
    name: "{{ rtorrent_user }}"
    group: "{{ rtorrent_group }}"
    comment: "rtorrent user"
    home: "{{ rtorrent_home }}"
    shell: /bin/bash

- name: create rtorrent directories
  sudo: yes
  sudo_user: "{{ rtorrent_user }}"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ rtorrent_download_dir }}"
    - "{{ rtorrent_session_dir }}"
    - "{{ rtorrent_watch_dir }}"
    - "{{ rtorrent_complete_dir }}"

- name: configure rtorrent
  sudo: yes
  sudo_user: "{{ rtorrent_user }}"
  template:
    src: rtorrent.rc.j2
    dest: "{{ rtorrent_home }}/.rtorrent.rc"
    owner: "{{ rtorrent_user }}"
    group: "{{ rtorrent_group }}"
    mode: 0644

- name: create rtorrent service
  sudo: yes
  template:
    src: rtorrent.j2
    dest: /etc/init.d/rtorrent
    owner: root
    group: root
    mode: 0755

- name: start rtorrent service
  sudo: yes
  service:
    name: rtorrent
    state: started
    enabled: yes
