---
# tasks file for ansible-rtorrent

- name: "install rtorrent"
  become: yes
  package:
    name: rtorrent
    state: present
  tags:
    - install

- name: "create rtorrent group"
  become: yes
  group:
    name: "{{ rtorrent_group }}"
  tags:
    - install

- name: "create rtorrent user"
  become: yes
  user:
    name: "{{ rtorrent_user }}"
    group: "{{ rtorrent_group }}"
    comment: "rtorrent user"
    home: "{{ rtorrent_user_home }}"
    shell: /bin/bash
  tags:
    - install

- name: "create rtorrent directories"
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rtorrent_user }}"
    group: "{{ rtorrent_group }}"
  with_items:
    - "{{ rtorrent_directory_download }}"
    - "{{ rtorrent_directory_session }}"
    - "{{ rtorrent_directory_watch }}"
  tags:
    - install

- name: "configure rtorrent"
  become: yes
  template:
    src: rtorrent.rc.j2
    dest: "{{ rtorrent_user_home }}/.rtorrent.rc"
    owner: "{{ rtorrent_user }}"
    group: "{{ rtorrent_group }}"
    mode: 0644
  tags:
    - configuration

- name: "install tmux"
  become: yes
  package:
    name: tmux
    state: present
  tags:
    - service

- name: "Debian | create rtorrent service"
  become: yes
  template:
    src: rtorrent.j2
    dest: /etc/init.d/rtorrent
    owner: root
    group: root
    mode: 0755
  when:
    ansible_os_family == "Debian"
  tags:
    - service

- name: "start rtorrent service"
  become: yes
  service:
    name: rtorrent
    state: started
    enabled: yes
  tags:
    - service
